server:
  port: 8089
spring:
  application:
    name: order-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/youle
    username: root
    password: 150154
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ly:
  jwt:
    pubKeyPath: D:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workerId: 1
    dataCenterId: 1
