server:
  port: 8082
spring:
  application:
    name: upload-service
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1