server:
  port: 8091
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/youle
    username: root
    password: 150154
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:10086/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1